#!/bin/sh

# Exit if any subcommand fails
set -e

DIR=$PWD

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

# React Native
cd ./client
pwd
echo "${GREEN}=====> Installing Node dependencies"
npm install
cd $DIR

# Flask
# echo "${GREEN}=====> Installing Python 3.10"
# sudo apt update && sudo apt upgrade -y
# sudo apt install software-properties-common -y
# sudo add-apt-repository ppa:deadsnakes/ppa
# sudo apt install python3.10

cd ./server
pwd
echo "${GREEN}=====> Installing Python dependencies"
python3 -m venv venv
ls venv
. ./venv/bin/activate
pip install -r requirements.txt
cd $DIR

# Local MongoDB
echo "${GREEN}=====> Installing MongoDB locally"
if [! -f /usr/bin/mongod ]; then
    sudo apt-get install gnupg
    wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
    sudo echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
    sudo apt-get update
    sudo apt-get install -y mongodb-org
    sudo apt autoremove && apt clean
    mkdir /data /data/db
    # sudo ufw allow proto tcp from any to any port 27017
    # sudo ufw enable
    sudo systemctl enable mongod
    sudo service mongod start

    
    # echo "Username for your Mongo DB admin account (DONOT use ampersands -> @)?"
    # read mongo_admin_user
    
    # echo "What is the password you want to set for $mongo_admin_user (DONOT use ampersands -> @)?"
    # read mongo_admin_pwd 
    
    # echo "User name will be set to $mongo_admin_user and password to $mongo_admin_pwd."
    
    # sudo mongo "admin" --eval "db.createUser({'user':'$mongo_admin_user','pwd':'$mongo_admin_pwd','roles': ['userAdminAnyDatabase','readWriteAnyDatabase']})"  
    
    # sudo echo ' ' >> /etc/mongod.conf
    # sudo echo 'security:' >> /etc/mongod.conf
    # sudo echo '  authorization: enabled' >> /etc/mongod.conf  
    
    # sudo service mongod restart
fi
