name: Flask
# Triggered when code is pushed to any branch in a repository
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  push: 
    branches:
      - main

jobs:
  test-flask:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MONGODB_URL: "${{ secrets.MONGODB_URL }}"

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: python -m pytest --cov-report term --cov=server/tests/
          debug: true

      