name: Mobile

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        working-directory: ./client

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Android APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Run tests
        run: npm run test
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Aab
          path: android/app/build/outputs/bundle/release/app-release.aab



  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        working-directory: ./client

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build iOS app
        run: cd ios && pod install && xcodebuild clean build -workspace MyApp.xcworkspace -scheme MyApp -configuration Release -sdk iphoneos -quiet

      - name: Run tests
        run: npm run test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-artifacts
          path: ios/build/Release-iphoneos/MyApp.ipa